# Generated by Django 2.0.6 on 2018-08-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('mood_type', models.CharField(choices=[('T', 'Text'), ('I', 'Image'), ('B', 'block_quote')], default='T', max_length=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='./image/mood/%Y/%m/%d/')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
    ]
