# Generated by Django 2.0.6 on 2018-10-28 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='summery',
            new_name='summary',
        ),
    ]
