# Generated by Django 2.0.6 on 2018-06-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New page', max_length=8, verbose_name='标题')),
                ('url', models.CharField(blank=True, max_length=4096, null=True, verbose_name='指向链接')),
                ('show_order', models.SmallIntegerField(default=0, verbose_name='展示顺序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '导航条',
                'verbose_name_plural': '导航条',
                'ordering': ['show_order', '-create_time'],
            },
        ),
    ]
